### ISSUE TITLE
Hitting the back button doesn't dismiss the sheet.

### ISSUE THREAD

**Issue by evant** [Flipboard/bottomsheet#10]
I'd expect it to work like the navigation drawer layout.

**Comment by hzsweers** [comment]
Unfortunately there's no easy way to handle this since the sheet is part of the activity's view hierarchy. We handle this in a base activity class, and you can see [an example in the sample code's `MainActivity`](https://github.com/Flipboard/bottomsheet/blob/master/bottomsheet-sample/src/main/java/com/flipboard/bottomsheet/sample/MainActivity.java#L61-L72)

It's not pretty, but unless `Activity` has a secret `addOnBackPressListener()` API that we're not aware of, I don't see any better solutions. Open to ideas though, any thoughts?

**Comment by evant** [comment]
Of course there is a way to do this, DrawerLayout does. You have to override `onKeyDown()` and `onKeyUp()` and listen for `keyCode == KeyEvent.KEYCODE_BACK`. See http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.3_r1/android/support/v4/widget/DrawerLayout.java#DrawerLayout.onKeyDown%28int%2Candroid.view.KeyEvent%29

**Comment by hzsweers** [comment]
Ah true, I always forget it shows up as a KeyEvent. We're going to look into that PR tomorrow, thanks for the suggestion!

**Comment by KishoreReddydhana** [comment]
@Override
    public void onBackPressed() {
        if (mBottomSheetBehavior.isHideable()) {
            super.onBackPressed();
        }else {
            mBottomSheetBehavior.setState(BottomSheetBehavior.STATE_COLLAPSED);
        }
    }

**Comment by phucnguyensna** [comment]
class BottomSheet : BottomSheetDialogFragment() {

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        return object: BottomSheetDialog(requireContext(), theme) {
            override fun onBackPressed() {
                // Handle backpress in here
            }
        }
    }
}
