### ISSUE TITLE
Bottom sheet not opening from DialogFragment

### ISSUE THREAD

**Issue by ShivamDev31** [Flipboard/bottomsheet#163]
Hi,

First of all thanks for the awesome library.
I'm facing two issues.

1.) BottomSheet is not opening at all. This is my code : https://gist.github.com/ShivamDev31/6526827e6fe531870310279ce5d41a19

I've a dialog and 2 radio buttons, on click on one of them I'm trying to open BottomSheet but its not opening at all, When I changed the type From BottomSheetFragment to DialogFragment then it showed a dialog.
Please have a look at the code and let me know if I'm doing anything wrong, followed the sample properly.

2.) Other issue is BottomSheetLayout is the root layout of dialog_booking and its not wrapping it height, I tried everything possible but its opening full screen. Even I hardcoded its height even then its opening full screen.

**Comment by markrietveld** [comment]
Hi @ShivamDev31. I'm happy this library is useful for you!

This issue tracker is for issues with the library, not for help debugging your own project. Your best bet for that is probably StackOverflow, or a similar website. Your first question doesn't seem to be a bug in the library, but since I looked at it: I think the first issue might be because of [this](https://gist.github.com/ShivamDev31/6526827e6fe531870310279ce5d41a19#file-bookingdialog-java-L80) line. It looks like the bottomsheet fragment is being added to the Activity instead of the fragment that has the `BottomSheetLayout`. Try `getChildFragmentManager()` instead of `getActivity().getSupportFragmentManager()`. Your sample code is incomplete, so I'm guessing here.

For your second point: `BottomSheetLayout` extends `FrameLayout`, and it doesn't override any of the layout code, so I don't think your bug is in this library. Dialog sizes can be complicated, so it might be better to avoid trying to put a lot of layout code in a dialog. Either way, I think you're better off on StackOverflow for this question too.
