### ISSUE TITLE
Allow peek content to scroll

### ISSUE THREAD

**Issue by Anatidae-Project** [Flipboard/bottomsheet#5]
First, great lib. Thanks. 

I think it would be great to allow peeked content to scroll. Similar to the behavior when expanded, when you hit the end of the scrollable, then it pulls open to an expanded view. Definately as a state switch, because it's more of an edge case.

Also, to add to this, I think it would be super cool to define a second sheet that hangs below the first (or just wherever you want) that animates in as you move from peeked to expanded. Could be cool.

**Comment by hzsweers** [comment]
Can you give some use cases for either of these?

**Comment by Anatidae-Project** [comment]
Sure. In my case I'm extending bottom sheet to make a shopping cart.

When an item is added, the cart slides up into "peek". This basically is a list view. I've extended the peek size to either be the height of this product list or the maximum size that would be found if the view was expanded. Conversely, the product scrollview also sizes itself to the maximum size of the parent view too.

The end result is a a scroll list of products. When drag the view into an "expanded" state the payment methods from your account are revealed below and you've moved into checkout mode. If you drag back down you move back into cart mode. If you dismiss the view you're back into buy mode. 

So in my case, I need to have a similar action to expanded. Where while in peeked if you drag up or down, it passes that event to the sheet unless the sheet isn't scrollable, upon which it then drags the bottomSheetView into expanded or hidden states. 

This is a very cool library and I think it would also be very handy to further add a dynamic element to attach it to any side. I could see uses with top-down peeks as well as left or right peeks.

Again, thanks for the open source.

**Comment by hzsweers** [comment]
This wouldn't really work with how the library works. When the bottom sheet is created, its height is actually the same as the parent. This creates an issue where if you wanted to scroll the list in its peeked state, the bottom ___ items of the list would conceivably never be visible in the peeked portion, since they're considered visible in the context of the whole sheet itself. The sheet isn't *really* expanding when you pull it up, rather you're just translating it up from off-screen.

A potential work around for this would maybe be to allow for scrolling until it hits the bottom, and then translating the sheet up. I think this behavior would be weird and not exactly obvious, so I don't think it's something we want to figure out just for a niche use case. You'd probably be better off extending `BottomSheetLayout` and implementing this behavior yourself.

> I think it would also be very handy to further add a dynamic element to attach it to any side

There's something for that in the material spec and support library already. It's called the Navigation Drawer ;)

**Comment by hzsweers** [comment]
Going to close this for now, we can revisit if more people express an interest.
