### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by TheFinestArtist** [Flipboard/bottomsheet#69]
Such as 
selector for grid/list item, 
grid padding, 
progress bar while loading packages, 
image picker infinite loading, 
dim, 
grid/list hiding scrollbar...

**Comment by hzsweers** [comment]
Some of these things (selector, padding, etc) will be configurable via styleables at some point (#39). The others are better left to the user to implement themselves. We're going to keep the library simple with an eye towards extensibility, rather than try to predict all the possible use cases and UIs people could want.

**Comment by koustuvsinha** [comment]
@hzsweers how to configure Dim via BottomSheet layout?

**Comment by krhckd93** [comment]
Is it possible, through the library, to dim the whole activity/screen and not just content view?
