### ISSUE TITLE
The height of the peeked sheet is too small when the sheet is shown after keyboard is dismissed

### ISSUE THREAD

**Issue by raylee4204** [Flipboard/bottomsheet#84]
When the soft keyboard is already showing, and I show the image picker sheet, the height of the peeked sheet is too small that it cuts off the contents initially.

The following is the correct height if the keyboard has been never displayed.
![device-2015-11-19-122932](https://cloud.githubusercontent.com/assets/2085389/11278519/64a57d58-8eb9-11e5-932f-8a16843b2010.png)

This is what happens when the sheet tries to show while the keyboard is dismissing
![device-2015-11-19-122946](https://cloud.githubusercontent.com/assets/2085389/11278521/66093d10-8eb9-11e5-936e-d6ebe63c3b4c.png)

**Comment by hzsweers** [comment]
What configuration do you have for your activity? AdjustPan? Resize?

**Comment by raylee4204** [comment]
It's set to default.But I'm using a transparent theme

**Comment by hzsweers** [comment]
Transparent theme shouldn't make a different. What is "default" in this case?

**Comment by raylee4204** [comment]
Default as in no specific configuration is set.

**Comment by markrietveld** [comment]
This is because the peeked state height is not updated if the height if the entire layout changes while the sheet is open. I'm not sure it should automatically updated on layout, it might lead to jarring visuals. I'm open to arguments for either

In the mean time @raylee4204, I recommend calling `setPeekSheetTranslation(pixels)` before opening the sheet. This allows you define a good value for your use case in your dimens.xml

**Comment by raylee4204** [comment]
@markrietveld I think it should. At least on keyboard open/close event

**Comment by hzsweers** [comment]
Folding this into #100 since I think they're probably the same issue.
