### ISSUE TITLE
Request: add shadow for the bottom sheet top area on pre-Lollipop, and make it optional for all versions

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Flipboard/bottomsheet#94]
As described here:
https://www.google.com/design/spec/components/bottom-sheets.html#
Notice that on some cases (as written in the guidelines), the shadow should not be shown (no matter which version of Android is used).

There should be a shadow for the bottom sheet even on pre-Lollipop, and as shown on Google's apps, like Google Maps :

![device-2015-12-08-101002](https://cloud.githubusercontent.com/assets/5357526/11650693/e82a2c4e-9d93-11e5-8ff8-76bcdbfdcabb.png)
(tested on G2 with Android 4.2) 

I've tried to talk about it here:
https://github.com/Flipboard/bottomsheet/issues/93
but I was suggested to use a CardView. Using CardView can't help, becuase it affects all sides, and not just the top side of the bottom sheet.

Please add a shadow for the various classes shown on "bottomsheet-commons", and make it optional (so that if they are customized to be non-rectangular shapes, it won't show a weird straight shadow). All of them are rectangle-shaped, so it should be ok to use the same shadow.

**Comment by AndroidDeveloperLB** [comment]
I think it's a simple gradient that's used, so it should be relatively easy to add.

**Comment by MatFl** [comment]
It's not that simple, because on tablets, were the bottom sheet does not span the entire screen, the shadow would also be needed on the sides.

**Comment by AndroidDeveloperLB** [comment]
@MatFl So if there is a different approach for tablets, they should have their own solution, just like they got a special treatment on other cases.

BTW, how do I add the shadow on BottomSheetFragment , for example? 
The docs say it should be for a view :
https://github.com/Flipboard/bottomsheet/wiki/Recipes
But why is it needed, if it works only on Lollipop and above, and I could just add elevation to the view in XML, and that's it?

**Comment by hzsweers** [comment]
The docs only specify a spec for elevation, which doesn't exist pre-lollipop. As discussed in the previous thread, we will not be backporting elevation. If it's as easy as adding a gradient, then developers can easily add it themselves. I think you'll find that it's not though, otherwise Google wouldn't have created a dedicated cardview library with special shadow implementations just to achieve this effect. 

This would, at the bare minimum, add another layer to the view hiearachy that we don't want to impose on users or maintain. 

Just because it's in the Google maps app doesn't mean it's practical or trivial to add for a general use case library. We are also not going to build that UI for you. Please put more consideration into what you're asking, and accept that this is not happening.
