### ISSUE TITLE
Bug: "scrollingDown" should actually be called "scrollingUp" in the code

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Flipboard/bottomsheet#96]
if you scroll down, the deltaY is positive, as you try to show the content below the current content.

The current code shows this in BottomSheetLayout.java :

            // If we are scrolling down and the sheet cannot scroll further, go out of expanded mode.
            boolean scrollingDown = deltaY < 0;

Even the description is opposite the the correct logic. If you scroll down, you actually go to expanded mode, and can't exit it.

The purpose of scroll-down is to show the content below. Since the touch events do the opposite (to scroll down, you move the finger up), it could be confusing

**Comment by hzsweers** [comment]
This is not a bug, rather just a naming opinion. I think you are also confused. The statement `if you scroll down, the deltaY is positive` is just incorrect.

DeltaY is the direction and translation of the MotionEvent. When scrolling down, that delta is negative because the actually touch is moving "up". Hence, the naming and corresponding logic make sense.

**Comment by AndroidDeveloperLB** [comment]
It is correct. Just put a log and you will see the value of "deltaY". It will become positive when I scroll down, and not negative.

Just add this:

            Log.d("AppLog", "deltaY:"+deltaY+" scrollingDown:"+scrollingDown);

**Comment by hzsweers** [comment]
It's not, `scrollingDown` is referring to the user interaction with the sheet. `deltaY` is referring to the motion event delta. Scrolling the sheet view down has a touch event with a negative y delta motion event. I am not going to argue semantics with you.
